### ISSUE TITLE
SyntaxError: Unexpected token ')' in Safari

### ISSUE THREAD

**Issue by WouterSioen** [rauchg/slackin#132]
The "get my invite" form does not work in Safari. I get this error in my console: `SyntaxError: Unexpected token ')'` in client.js on line 45.

Note that if I click on the error message, it shows and highlights line 46 instead of line 45.

`window.setTimeout(() => {`

**Comment by WouterSioen** [comment]
It looks like it's caused by the new arrow syntax for anonymous functions:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility

**Comment by limulus** [comment]
I could very well be wrong but it looks to me like `lib/assets/client.js` should be getting transpiled by Babel when `gulp` is run. Which means that arrow function should get converted to an ES5 anonymous function automatically. Are you intentionally bypassing the transpilation? If not, then the fix is probably needed in either the gulpfile, babel settings, or pointing the browser to the transpiled `client.js` if it is somehow wrong.
