### ISSUE TITLE
How to get a legacy token for Slackin

### ISSUE THREAD

**Issue by nannanli** [rauchg/slackin#412]
Slack no longer support the use of legacy tokens and replace them with Slack apps. I want to deploy Slackin to IBM Bluemix. I'm new to Slack and Slackin. Wondering if anyone could advise how to create a legacy token for use now. Thanks!

**Comment by mhuebert** [comment]
It looks like you can still create legacy tokens until May 5th here: https://api.slack.com/legacy/custom-integrations/legacy-tokens

After legacy tokens are deprecated, it seems only Enterprise Slack teams will be able to use auto-invite flows/apps, because the `admin.users.invite` api method is restricted: https://api.slack.com/methods/admin.users.invite

**Comment by nannanli** [comment]
Thank you @mhuebert ! I managed to create the legacy token just now.
